## https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
## https://github.com/helm/charts/tree/master/stable/prometheus-operator
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator 
  namespace: prometheus
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.1.0
  values: 
    prometheusSpec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values: 
                - systemnodes
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: managed-premium
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi

    grafana:
      ingress:
          ## If true, Grafana Ingress will be created
          ##
          enabled: false
          path: /grafanaint
          annotations: 
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      persistence:
        enabled: true
        type: pvc
        storageClassName: managed-premium
      dashboardProviders: 
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          kubernetes-cluster-monitoring:
            # Ref: https://grafana.com/dashboards/3119 - Kubernetes cluster monitoring (via Prometheus)
            gnetId: 3119
            revision: 2
            datasource: Prometheus
          kubernetes-cluster:
            # Ref: https://grafana.com/dashboards/6417 - Kubernetes cluster 
            gnetId: 6417
            revision: 1
            datasource: Prometheus
          node-exporter:
            # Ref: https://grafana.com/dashboards/6417 - Kubernetes cluster 
            gnetId: 11074
            revision: 1
            datasource: Prometheus
        

