## https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: secretstore-csi-driver
  namespace: secretstore
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: secretstore-csi-driver
  chart:
    repository: https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
    name: secretstore-csi-driver
    version: 0.0.8

      



