## https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-internal
  namespace: ingress
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: nginx-internal
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.1
  values:
    defaultBackend:
      enabled: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
    controller:
      podLabels:
        lbtype: internal
      ingressClass: nginx-internal
      scope:
        enabled: true
      autoscaling:
        enabled: false
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
      service:
        enableHttp: false
        loadBalancerIP: ""
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enable: true
      replicaCount: 1
      nodeSelector:
        agentpool: systemnodes
      defaultBackend:
        nodeSelector: 
          agentpool: systemnodes
      



